language: ruby
rvm:
  - 2.2
  - 2.3
  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2
gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_head.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
bundler_args: --without local_development
before_install: gem install bundler
